name: Deploy Application

on:

  workflow_dispatch:

  repository_dispatch:
    types:
      - deploy-ui
      - deploy-zuul
      - deploy-offers
      - deploy-shoes
      - deploy-wishlist
      - deploy-cart

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Print Payload
        run: |
          echo "Service:"
          echo "${{ github.event.client_payload.service }}"

          echo "Tag:"
          echo "${{ github.event.client_payload.tag }}"

      - name: Deploy To EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd ~/deployment-repo

            git pull origin main

            SERVICE="${{ github.event.client_payload.service }}"
            TAG="${{ github.event.client_payload.tag }}"

            echo "==============================="
            echo "SERVICE = $SERVICE"
            echo "TAG     = $TAG"
            echo "==============================="

            case "$SERVICE" in

              ui)
                sed -i "s/^UI_TAG=.*/UI_TAG=$TAG/" .env
                ;;

              zuul)
                sed -i "s/^ZUUL_TAG=.*/ZUUL_TAG=$TAG/" .env
                ;;

              offers)
                sed -i "s/^OFFERS_TAG=.*/OFFERS_TAG=$TAG/" .env
                ;;

              shoes)
                sed -i "s/^SHOES_TAG=.*/SHOES_TAG=$TAG/" .env
                ;;

              wishlist)
                sed -i "s/^WISHLIST_TAG=.*/WISHLIST_TAG=$TAG/" .env
                ;;

              cart)
                sed -i "s/^CART_TAG=.*/CART_TAG=$TAG/" .env
                ;;

              *)
                echo "Unknown Service: $SERVICE"
                exit 1
                ;;

            esac

            echo "========== UPDATED ENV =========="
            cat .env

            aws ecr get-login-password \
            --region ap-south-2 \
            | docker login \
            --username AWS \
            --password-stdin \
            663566123253.dkr.ecr.ap-south-2.amazonaws.com

            docker network inspect micro-net >/dev/null 2>&1 || \
            docker network create micro-net

            docker compose pull

            docker compose up -d

            echo "========== RUNNING CONTAINERS =========="
            docker ps

            echo "========== COMPOSE CONFIG =========="
            docker compose config