name: Deploy Application

on:

  push:
    branches:
      - main

  workflow_dispatch:

  repository_dispatch:
    types:
      - deploy-ui

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Print Payload
        run: |
          echo "Service:"
          echo "${{ github.event.client_payload.service }}"

          echo "Tag:"
          echo "${{ github.event.client_payload.tag }}"

      - name: Deploy To EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd ~/deployment-repo

            git pull origin main

            sed -i "s/^UI_TAG=.*/UI_TAG=${{ github.event.client_payload.tag }}/" .env

            echo "===== UPDATED ENV ====="
            cat .env

            aws ecr get-login-password \
            --region ap-south-2 \
            | docker login \
            --username AWS \
            --password-stdin \
            663566123253.dkr.ecr.ap-south-2.amazonaws.com

            docker network inspect micro-net >/dev/null 2>&1 || \
            docker network create micro-net

            docker compose pull

            docker compose up -d

            docker ps